/**
 * Drizzle schema for the multi-tenant Facebook auto-posting SaaS.
 *
 * Conventions:
 *  - All `*_at` columns are `timestamp with time zone`.
 *  - All foreign keys cascade on delete (deleting a user removes all their data).
 *  - Primary keys are uuid via `pgcrypto`'s `gen_random_uuid()` (Supabase preinstalls it).
 *  - Data isolation is enforced at the application layer by filtering on `user_id`.
 */
import {
  boolean,
  date,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
  index,
  uuid,
} from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';

/* ------------------------------------------------------------------ */
/* Enums                                                              */
/* ------------------------------------------------------------------ */

export const campaignStatusEnum = pgEnum('campaign_status', [
  'draft',
  'running',
  'paused',
  'done',
  'cancelled',
  'error',
]);

export const jobStatusEnum = pgEnum('job_status', [
  'pending',
  'running',
  'success',
  'failed',
  'skipped',
]);

export const logLevelEnum = pgEnum('log_level', ['info', 'warn', 'error']);

/**
 * Channel for a post: which kind of FB surface it targets.
 * - 'group' — posted to a Facebook group (the original WizardPosts flow,
 *   driven by the local Playwright Worker via /api/worker/next-job).
 * - 'page'  — posted to a Facebook Page the user owns, via the Graph
 *   API. Generated by AI on a schedule, requires manual approval before
 *   publish.
 * Default 'group' so all pre-existing rows keep their semantics.
 */
export const channelEnum = pgEnum('channel', ['group', 'page']);

/* ------------------------------------------------------------------ */
/* NextAuth Drizzle adapter tables                                    */
/* https://authjs.dev/getting-started/adapters/drizzle                */
/* ------------------------------------------------------------------ */

export const users = pgTable('users', {
  id: uuid('id').primaryKey().default(sql`gen_random_uuid()`),
  name: text('name'),
  email: text('email').notNull().unique(),
  emailVerified: timestamp('email_verified', { withTimezone: true }),
  image: text('image'),
  fbConnected: boolean('fb_connected').notNull().default(false),
  fbUserName: text('fb_user_name'),
  createdAt: timestamp('created_at', { withTimezone: true })
    .notNull()
    .defaultNow(),
  // Per-user safety defaults — applied to new campaigns and used by the
  // worker as fallback throttling when a campaign-specific value is absent.
  dailyCap: integer('daily_cap').notNull().default(12),
  minDelayMs: integer('min_delay_ms').notNull().default(300_000),
  maxDelayMs: integer('max_delay_ms').notNull().default(900_000),
  workHoursStart: integer('work_hours_start').notNull().default(9),
  workHoursEnd: integer('work_hours_end').notNull().default(22),
  maxConsecutiveFails: integer('max_consecutive_fails').notNull().default(3),
  typingMinMs: integer('typing_min_ms').notNull().default(50),
  typingMaxMs: integer('typing_max_ms').notNull().default(150),
});

export const accounts = pgTable(
  'accounts',
  {
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    type: text('type').notNull(),
    provider: text('provider').notNull(),
    providerAccountId: text('provider_account_id').notNull(),
    refresh_token: text('refresh_token'),
    access_token: text('access_token'),
    expires_at: integer('expires_at'),
    token_type: text('token_type'),
    scope: text('scope'),
    id_token: text('id_token'),
    session_state: text('session_state'),
  },
  (t) => ({
    pk: primaryKey({ columns: [t.provider, t.providerAccountId] }),
  }),
);

export const sessions = pgTable('sessions', {
  sessionToken: text('session_token').primaryKey(),
  userId: uuid('user_id')
    .notNull()
    .references(() => users.id, { onDelete: 'cascade' }),
  expires: timestamp('expires', { withTimezone: true }).notNull(),
});

export const verificationTokens = pgTable(
  'verification_tokens',
  {
    identifier: text('identifier').notNull(),
    token: text('token').notNull(),
    expires: timestamp('expires', { withTimezone: true }).notNull(),
  },
  (t) => ({
    pk: primaryKey({ columns: [t.identifier, t.token] }),
  }),
);

/* ------------------------------------------------------------------ */
/* Worker tokens                                                      */
/* `token` column stores a bcrypt hash, never the plain token.        */
/* ------------------------------------------------------------------ */

export const workerTokens = pgTable(
  'worker_tokens',
  {
    id: uuid('id').primaryKey().default(sql`gen_random_uuid()`),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    token: text('token').notNull().unique(), // bcrypt hash
    // SHA-256 hex of the plain token. Deterministic, indexable, used as the
    // primary lookup key so we don't bcrypt-scan every row in the table on
    // every worker request. Nullable for rows created before this column
    // existed; those fall back to a (slow) bcrypt scan until rotated.
    tokenFp: text('token_fp'),
    name: text('name').notNull(),
    lastSeenAt: timestamp('last_seen_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    revokedAt: timestamp('revoked_at', { withTimezone: true }),
  },
  (t) => ({
    userIdx: index('worker_tokens_user_id_idx').on(t.userId),
    tokenFpIdx: index('worker_tokens_token_fp_idx').on(t.tokenFp),
  }),
);

/* ------------------------------------------------------------------ */
/* Posts                                                              */
/* ------------------------------------------------------------------ */

export const posts = pgTable(
  'posts',
  {
    id: uuid('id').primaryKey().default(sql`gen_random_uuid()`),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    text: text('text').notNull(),
    imageUrl: text('image_url'),
    /**
     * Optional short video to attach to the post. mp4/webm/mov, up to
     * the upload route's size cap. When set, the worker uploads it via
     * the same Photo/Video composer button as images; FB accepts either.
     * imageUrl takes precedence if both are set.
     */
    videoUrl: text('video_url'),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),

    // ---- Page-channel additions (Phase 1, einatural module) -----------
    // All new columns are nullable / have defaults so existing rows are
    // untouched and the existing 'group' code path keeps working.
    channel: channelEnum('channel').notNull().default('group'),
    // FK constraint added in the migration script (avoiding forward-ref
    // here because `pages` is declared after `posts` in this file).
    pageId: uuid('page_id'),
    imagePrompt: text('image_prompt'),
    captionVariants: jsonb('caption_variants'), // string[] generated by AI
    approvalStatus: text('approval_status'),
    // valid values for page-channel posts:
    //   'pending'   — awaiting human approval in /page/queue
    //   'approved'  — approved, queued for publish at scheduledAt
    //   'rejected'  — owner rejected, won't publish
    //   'skipped'   — passed the 09:30 cutoff without approval
    //   'published' — successfully posted to FB Page
    //   'failed'    — publisher gave up after 3 retries
    // Null for group-channel posts (they use the jobs table for status).
    approvedAt: timestamp('approved_at', { withTimezone: true }),
    scheduledAt: timestamp('scheduled_at', { withTimezone: true }),
    fbPostId: text('fb_post_id'),
    retryCount: integer('retry_count').notNull().default(0),
  },
  (t) => ({
    userIdx: index('posts_user_id_idx').on(t.userId),
    // Drives the publisher cron (every 5 min): pick approved posts whose
    // scheduledAt has passed and that haven't been published yet. Also
    // serves the queue UI's pending-list query.
    publishLookupIdx: index('posts_publish_lookup_idx').on(
      t.channel,
      t.approvalStatus,
      t.scheduledAt,
    ),
  }),
);

/* ------------------------------------------------------------------ */
/* Groups                                                             */
/* unique-per-user: (user_id, url)                                    */
/* ------------------------------------------------------------------ */

export const groups = pgTable(
  'groups',
  {
    id: uuid('id').primaryKey().default(sql`gen_random_uuid()`),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    url: text('url').notNull(),
    name: text('name'),
    tag: text('tag'),
    lastPostedAt: timestamp('last_posted_at', { withTimezone: true }),
    successCount: integer('success_count').notNull().default(0),
    failCount: integer('fail_count').notNull().default(0),
    active: boolean('active').notNull().default(true),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    userUrlUnique: uniqueIndex('groups_user_id_url_unique').on(t.userId, t.url),
    userIdx: index('groups_user_id_idx').on(t.userId),
    tagIdx: index('groups_tag_idx').on(t.tag),
    activeIdx: index('groups_active_idx').on(t.active),
  }),
);

/* ------------------------------------------------------------------ */
/* Pages — Facebook Pages connected via Graph API.                    */
/*                                                                    */
/* The einatural module: a user owns a real FB Page and grants us a   */
/* long-lived Page Access Token. We then publish AI-generated posts   */
/* directly via Graph API (no Worker / Playwright needed for this     */
/* surface — the user owns the Page so Development Mode is enough).   */
/*                                                                    */
/* The token is stored encrypted (AES-256-GCM via lib/crypto.ts);     */
/* never read it raw outside the decrypt() helper.                    */
/*                                                                    */
/* brand_kit holds tone, audience, pillars, hashtags, image style and */
/* publish slots — used by the AI generation cron to keep voice       */
/* consistent across posts. Schema-less jsonb so we can iterate the   */
/* shape without migrations.                                          */
/* ------------------------------------------------------------------ */

export const pages = pgTable(
  'pages',
  {
    id: uuid('id').primaryKey().default(sql`gen_random_uuid()`),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    fbPageId: text('fb_page_id').notNull(),
    pageName: text('page_name').notNull(),
    accessToken: text('access_token').notNull(), // AES-256-GCM ciphertext
    tokenExpiresAt: timestamp('token_expires_at', { withTimezone: true }),
    brandKit: jsonb('brand_kit').notNull(),
    active: boolean('active').notNull().default(true),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    userIdx: index('pages_user_id_idx').on(t.userId),
    activeIdx: index('pages_active_idx').on(t.active),
  }),
);

/* ------------------------------------------------------------------ */
/* Campaigns                                                          */
/* ------------------------------------------------------------------ */

export const campaigns = pgTable(
  'campaigns',
  {
    id: uuid('id').primaryKey().default(sql`gen_random_uuid()`),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    postId: uuid('post_id')
      .notNull()
      .references(() => posts.id, { onDelete: 'cascade' }),
    status: campaignStatusEnum('status').notNull().default('draft'),
    dailyCap: integer('daily_cap').notNull().default(12),
    minDelayMs: integer('min_delay_ms').notNull().default(300_000),
    maxDelayMs: integer('max_delay_ms').notNull().default(900_000),
    workHoursStart: integer('work_hours_start').notNull().default(9),
    workHoursEnd: integer('work_hours_end').notNull().default(22),
    textVariations: boolean('text_variations').notNull().default(false),
    scheduledStartAt: timestamp('scheduled_start_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    startedAt: timestamp('started_at', { withTimezone: true }),
    finishedAt: timestamp('finished_at', { withTimezone: true }),
    lastError: text('last_error'),
  },
  (t) => ({
    userIdx: index('campaigns_user_id_idx').on(t.userId),
    statusIdx: index('campaigns_status_idx').on(t.status),
  }),
);

/* ------------------------------------------------------------------ */
/* Jobs                                                               */
/* ------------------------------------------------------------------ */

export const jobs = pgTable(
  'jobs',
  {
    id: uuid('id').primaryKey().default(sql`gen_random_uuid()`),
    campaignId: uuid('campaign_id')
      .notNull()
      .references(() => campaigns.id, { onDelete: 'cascade' }),
    groupId: uuid('group_id')
      .notNull()
      .references(() => groups.id, { onDelete: 'cascade' }),
    status: jobStatusEnum('status').notNull().default('pending'),
    attempts: integer('attempts').notNull().default(0),
    scheduledAt: timestamp('scheduled_at', { withTimezone: true }),
    startedAt: timestamp('started_at', { withTimezone: true }),
    finishedAt: timestamp('finished_at', { withTimezone: true }),
    resultMessage: text('result_message'),
    screenshotPath: text('screenshot_path'),
    claimedByToken: uuid('claimed_by_token').references(() => workerTokens.id, {
      onDelete: 'set null',
    }),
    // Worker-side classification of why a job failed (composer_not_found,
    // login_required, fb_blocked, network_error, etc.). Used by the auto-pause
    // logic in countConsecutiveFailures so transient kinds don't pause a
    // working campaign over a single DOM drift. Null on success or pre-iter5
    // legacy rows.
    failureKind: text('failure_kind'),
    /**
     * Last time the worker re-visited the group to verify whether a
     * post that ended up in moderator-approval queue has since been
     * approved (post visible) or rejected. Null = never rechecked.
     * The cloud cron + worker periodic loop drive this.
     */
    lastRecheckedAt: timestamp('last_rechecked_at', { withTimezone: true }),
  },
  (t) => ({
    campaignIdx: index('jobs_campaign_id_idx').on(t.campaignId),
    statusIdx: index('jobs_status_idx').on(t.status),
    scheduledIdx: index('jobs_scheduled_at_idx').on(t.scheduledAt),
  }),
);

/* ------------------------------------------------------------------ */
/* Daily counters — composite PK (user_id, day)                       */
/* ------------------------------------------------------------------ */

export const dailyCounters = pgTable(
  'daily_counters',
  {
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    day: date('day').notNull(),
    postedCount: integer('posted_count').notNull().default(0),
  },
  (t) => ({
    pk: primaryKey({ columns: [t.userId, t.day] }),
  }),
);

/* ------------------------------------------------------------------ */
/* Logs                                                               */
/* user_id is nullable — system-level logs may have no owner.         */
/* ------------------------------------------------------------------ */

export const logs = pgTable(
  'logs',
  {
    id: uuid('id').primaryKey().default(sql`gen_random_uuid()`),
    userId: uuid('user_id').references(() => users.id, { onDelete: 'cascade' }),
    level: logLevelEnum('level').notNull(),
    source: text('source').notNull(),
    message: text('message').notNull(),
    meta: jsonb('meta'),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    userIdx: index('logs_user_id_idx').on(t.userId),
    levelIdx: index('logs_level_idx').on(t.level),
    createdIdx: index('logs_created_at_idx').on(t.createdAt),
  }),
);

/* ------------------------------------------------------------------ */
/* Inferred types                                                     */
/* ------------------------------------------------------------------ */

export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;

export type Account = typeof accounts.$inferSelect;
export type NewAccount = typeof accounts.$inferInsert;

export type Session = typeof sessions.$inferSelect;
export type NewSession = typeof sessions.$inferInsert;

export type VerificationToken = typeof verificationTokens.$inferSelect;
export type NewVerificationToken = typeof verificationTokens.$inferInsert;

export type WorkerToken = typeof workerTokens.$inferSelect;
export type NewWorkerToken = typeof workerTokens.$inferInsert;

export type Post = typeof posts.$inferSelect;
export type NewPost = typeof posts.$inferInsert;

export type Group = typeof groups.$inferSelect;
export type NewGroup = typeof groups.$inferInsert;

export type Campaign = typeof campaigns.$inferSelect;
export type NewCampaign = typeof campaigns.$inferInsert;

export type Job = typeof jobs.$inferSelect;
export type NewJob = typeof jobs.$inferInsert;

/* ------------------------------------------------------------------ */
/* Shortlinks — branded URL shortener with per-(post×group) attribution. */
/*                                                                     */
/* Two roles for a row:                                                */
/*   - PARENT: created by a user via /shortlinks/new. Stable slug      */
/*     they paste into post text. parent_id IS NULL, group_id IS NULL. */
/*   - CHILD: auto-created when a campaign starts and the post text    */
/*     contains a parent shortlink. One child per (parent × group).    */
/*     parent_id and group_id are set; slug is auto-generated.         */
/*                                                                     */
/* The redirect endpoint /l/<slug> resolves either form by slug. Click */
/* attribution per group works because the worker text-replaces        */
/* parent URLs with group-specific child URLs at posting time.         */
/* ------------------------------------------------------------------ */

export const shortlinks = pgTable(
  'shortlinks',
  {
    id: uuid('id').primaryKey().default(sql`gen_random_uuid()`),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    parentId: uuid('parent_id'),
    postId: uuid('post_id').references(() => posts.id, { onDelete: 'set null' }),
    groupId: uuid('group_id').references(() => groups.id, { onDelete: 'set null' }),
    jobId: uuid('job_id').references(() => jobs.id, { onDelete: 'set null' }),
    slug: text('slug').notNull().unique(),
    targetUrl: text('target_url').notNull(),
    label: text('label'),
    isActive: boolean('is_active').notNull().default(true),
    clickCount: integer('click_count').notNull().default(0),
    botClickCount: integer('bot_click_count').notNull().default(0),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    userIdx: index('shortlinks_user_id_idx').on(t.userId),
    parentIdx: index('shortlinks_parent_id_idx').on(t.parentId),
    postGroupIdx: index('shortlinks_post_group_idx').on(t.postId, t.groupId),
    activeUserIdx: index('shortlinks_user_active_idx').on(t.userId, t.isActive),
  }),
);

export const shortlinkClicks = pgTable(
  'shortlink_clicks',
  {
    id: uuid('id').primaryKey().default(sql`gen_random_uuid()`),
    shortlinkId: uuid('shortlink_id')
      .notNull()
      .references(() => shortlinks.id, { onDelete: 'cascade' }),
    clickedAt: timestamp('clicked_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    // sha256(ip + daily_salt) sliced to 32 chars. Lets us count distinct
    // visitors per day without storing actual IPs.
    ipHash: text('ip_hash'),
    userAgent: text('user_agent'),
    country: text('country'),
    deviceType: text('device_type'),
    referrer: text('referrer'),
    isBot: boolean('is_bot').notNull().default(false),
  },
  (t) => ({
    shortlinkTimeIdx: index('shortlink_clicks_shortlink_time_idx').on(
      t.shortlinkId,
      t.clickedAt,
    ),
    timeIdx: index('shortlink_clicks_time_idx').on(t.clickedAt),
  }),
);

export type Shortlink = typeof shortlinks.$inferSelect;
export type NewShortlink = typeof shortlinks.$inferInsert;
export type ShortlinkClick = typeof shortlinkClicks.$inferSelect;
export type NewShortlinkClick = typeof shortlinkClicks.$inferInsert;

export type DailyCounter = typeof dailyCounters.$inferSelect;
export type NewDailyCounter = typeof dailyCounters.$inferInsert;

export type Log = typeof logs.$inferSelect;
export type NewLog = typeof logs.$inferInsert;

export type CampaignStatus = (typeof campaignStatusEnum.enumValues)[number];
export type JobStatus = (typeof jobStatusEnum.enumValues)[number];
export type LogLevel = (typeof logLevelEnum.enumValues)[number];

export type Channel = (typeof channelEnum.enumValues)[number];

export type Page = typeof pages.$inferSelect;
export type NewPage = typeof pages.$inferInsert;

/**
 * Approval lifecycle for page-channel posts. Group-channel posts ignore
 * this column entirely (their lifecycle lives in the `jobs` table).
 */
export type PageApprovalStatus =
  | 'pending'
  | 'approved'
  | 'rejected'
  | 'skipped'
  | 'published'
  | 'failed';
